### ISSUE TITLE
BN0 mean and variance

### ISSUE THREAD

**Issue by HahTK** [cvjena/cnn-models#10]
I extracted the model parameters for the pre trained model and noticed that the computed mean and variance for the input BN layer is between 1000 - 1200 and 40k+ to 50k+ respectively. How is this possible given that the image RGB layers should have values between 0-255 ?

**Comment by MarcelSimon** [comment]
The mean and variance are scaled by a factor stored in net.params['data_bn'][2], that's 1000 in case of ResNet50.
Hence net.params['data_bn'][0].data, which is the mean, needs to be divided by that value to obtain the actual mean value. This scaling seems to be necessary due to the moving average calculation.
